name: "Ashok Kumar"
description: "Jembe Ashok - Kannada Actor - Theatre and Films, Acting Coach and Theatre Workshop, Leading Jembe - African Drum Musician in India, Shoonya Band"

permalink: pretty
highlighter: pygments
markdown: kramdown
