- type: music
  title: Jembe Course
  small: course.jpg 
  large: course_large.jpg
  alt: Jembe Course by Ashok
  role: This introduction course is to enable everyone to learn to play the Jembe - an african drum and use that as a medium to find the joy of playing together. This is typically held as a 8 or 16 session for 2 hours each, held on the weekends. <br> <br> No prior musical background is necessary. And if you don't have a jembe, they would be provided for the workshop duration.
  more: <a href="/outline/jembe_course.pdf">Jembe Course Outline</a> 
  link: 
  video: 

- type: music 
  title: Jembe Workshop
  small: workshop.jpg 
  large: workshop_large.jpg
  alt: Jembe Workshop by Ashok
  role: Music is about discovery – finding our own rhythm when we are alone or when we are part of a group. This workshop uses rhythm and music as a medium for team building and leadership skills.  It can be structured as either a half day session or a full day session. <br> <br> This jembe workshop is ideal for corporates, NGOs and education institutes in small group settings. 
  more: <a href="/outline/jembe_workshop.pdf">Jembe Workshop Outline</a> 
  link: 
  video: 

- type: music 
  title: Jembe One-to-One
  small: individual.jpg 
  large: individual_large.jpg
  alt: Jembe One-to-One Training by Ashok
  role: If you are interested in one - to - one coaching to learn the djembe, please contact me directly. Individual or small group classes are held at my place (close to PESIT college in Banashankari 3rd Stage, Bangalore) usually in the morning. <br> <br> This is for serious learners willing to learn the instrument through sustained coaching and practice.
  more: 
  link: 
  video: 

- type: acting
  title: Children Workshop
  small: children.jpg 
  large: children_large.jpg
  alt: Children Workshop by Ashok
  role: Theatre and music are both wonderful mediums to assist young people to address social, cultural and personal concerns. I have extensively worked with children and young adult in different educational context - to allow them to express, explore and enhance their personal & group skills. <br> <br> These can be designed as informal play-oriented sessions or formal theater or music sessions, say educational drama.
  more: <a href="/outline/educational_drama.pdf">Educational Drama Outline</a> 
  link: 
  video: 

- type: acting 
  title: Acting Course
  small: acting.jpg 
  large: acting_large.jpg
  alt: Acting Course by Ashok
  role: This course is designed for upcoming actors who have some acting experience in theatre or film medium. This will be held as an intensive workshop of about 15 sessions of 3 hours each, across two weeks. The number of actors will be restricted to 15 to ensure personalised attention can be provided. <br> <br> This will give each actor an opportunity to work on their specific areas of focus and improvement e.g. body language, voice and modulation, effective dialogue delivery etc. 
  more: <a href="/outline/acting_course.pdf">Acting Course Outline</a> 
  link: 
  video: 

- type: acting
  title: Utsmaya Workshop
  small: utsmaya.jpg 
  large: utsmaya_large.jpg
  alt: Utsmaya Workshop by Ashok
  role: This unique workshop experience is to enable anyone to flourish. I believe each of us have a seed in us that if provided the right nourishment and support can flower in its own unique way. In this workshop, we use three lenses - three different art forms of Roleplay (Theatre), Storytelling and Jembe (Music) - to get started on this journey. Each art form is used in a session as the chosen medium for expression, exploration and discovery.
  more: <a href="http://amitkaps.com/utsmaya">More about Utsmaya</a> 
  link: 
  video: 